//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Code/Scripts/Main/Input/Joystick.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Joystick : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Joystick()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Joystick"",
    ""maps"": [
        {
            ""name"": ""Controller"",
            ""id"": ""d98d9a16-4ede-4384-91c8-59ada4755b88"",
            ""actions"": [
                {
                    ""name"": ""Trigger"",
                    ""type"": ""Button"",
                    ""id"": ""55b78355-5069-4122-9671-b2b4da7fca06"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_1"",
                    ""type"": ""Button"",
                    ""id"": ""2f4160f3-64e2-4cf1-9667-46156e495b21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_2"",
                    ""type"": ""Button"",
                    ""id"": ""36d55365-4748-4972-96f9-d01b4ef491b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_3"",
                    ""type"": ""Button"",
                    ""id"": ""9fa5531b-a52f-4095-82bb-976b45899f46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Button_4"",
                    ""type"": ""Button"",
                    ""id"": ""16203514-ccd0-4936-acf5-11566a368b4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hut_1"",
                    ""type"": ""Value"",
                    ""id"": ""a7497aa5-2680-44ff-8fe7-b567060bdc6b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hut_2"",
                    ""type"": ""Value"",
                    ""id"": ""35d95d49-6692-4c5a-a7c3-0f90a1ed203e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Hut_3"",
                    ""type"": ""Value"",
                    ""id"": ""b23b2e8a-eb0e-468f-aa2d-bc233cdf1e37"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Axis"",
                    ""type"": ""Value"",
                    ""id"": ""2309dc56-6b54-4f07-bb58-1dba78c3492a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Number_1"",
                    ""type"": ""Button"",
                    ""id"": ""7ddccc34-1d01-4107-8d19-3fc48206a552"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_2"",
                    ""type"": ""Button"",
                    ""id"": ""5299813b-adc7-4070-ab40-e4fc5681fef9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_3"",
                    ""type"": ""Button"",
                    ""id"": ""8f85aa5d-392d-40b9-ab1c-d3db203ec5ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_4"",
                    ""type"": ""Button"",
                    ""id"": ""32820f25-b501-4e57-80e6-f903ac2d53e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_5"",
                    ""type"": ""Button"",
                    ""id"": ""3e695ecf-4683-44f0-a35a-3ec913fb8496"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Number_6"",
                    ""type"": ""Button"",
                    ""id"": ""6d8b15cd-4fa9-4796-b5ef-6f9a9ba328fe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Container_1"",
                    ""type"": ""Button"",
                    ""id"": ""3303805f-9260-4bd7-9fa5-c76faef902c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Container_2"",
                    ""type"": ""Button"",
                    ""id"": ""f1670f4c-5b9c-48a4-88f2-84a8df678b1b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Container_3"",
                    ""type"": ""Button"",
                    ""id"": ""0e649a25-582b-45a6-aae7-9437b2cf9a5b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Up"",
                    ""type"": ""Button"",
                    ""id"": ""522996fe-5696-498f-8578-bf9b1d906f9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Down"",
                    ""type"": ""Button"",
                    ""id"": ""46bdbf6e-82ea-4888-9a0a-defec71a6cb3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Collect_mode"",
                    ""type"": ""Button"",
                    ""id"": ""bc20c8b1-e9b3-4c88-96e6-28a68f5a9f4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""bb78dddc-bb86-47ee-95e8-bfbf8b2a87ad"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TriggerDown"",
                    ""type"": ""Button"",
                    ""id"": ""5cf8dac9-ce44-4149-8c62-f0b7ce555c53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Out"",
                    ""type"": ""Button"",
                    ""id"": ""15497b38-3fc6-48dc-bd51-b538405fffc5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AxisWasd"",
                    ""type"": ""Value"",
                    ""id"": ""391cfc57-5c4e-4446-8b7c-f0fc201e63df"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f2bb3140-c4f5-4432-874d-7f660e71abc4"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8368a198-ff95-4c04-baf3-e05ad186ddf8"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;Main"",
                    ""action"": ""Trigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cb4432c-f1ec-48fb-9f5c-6bdfd6a33c9e"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Button_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0152ac81-530b-41c5-8fd8-f4264adaee70"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Button_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bff3ff4c-4466-487a-832d-8b5ac89cf175"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button25"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Button_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""86766ec9-450d-4818-96e5-8b82b464ffc3"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Button_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f252ffc0-900a-4966-9431-852300d92bb5"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Button_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f09ce260-a3cd-4be1-892d-e619fb6a5797"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Button_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05106e80-7834-472c-b299-f72afaaae8c2"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Button_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a00cf29-0048-47bf-b39b-f9dd5bfde0e3"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Button_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Axis"",
                    ""id"": ""69a693f1-9231-446c-be29-4fa034bf90cc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6e3817e6-1fc8-4d85-ad53-d29fc6575436"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button16"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c407afc3-8efd-4607-8dda-25c8742b9e12"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button18"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f4af67f3-b68a-4a4a-9a59-c531302a9c3c"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button19"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d622719c-71c5-4840-b534-22710cae9cbc"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button17"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""KeyboardVector"",
                    ""id"": ""5a10369d-0926-42dc-9b80-3b92f923b5bc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""23969249-9aa9-444a-9411-8f922bca247f"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""0fc3fb67-b3e3-45f5-92a4-6744b537e68e"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d4f64655-c022-48e7-9b27-6aae5858ada3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1229c16b-ad9b-44a8-9856-5e30a8ba2db1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Axis"",
                    ""id"": ""9f208f5b-8e74-4846-a6e3-cec447433c0b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4e6c310b-4216-401f-a4e0-5ace6939c8b0"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1becf415-a9e3-45e3-85a6-49591a571e40"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f979bcc7-0517-41e2-9e65-334d1a02b97c"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5c7d247d-f0b1-47f8-b728-a909178d5c47"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Axis"",
                    ""id"": ""bd88e00b-f03c-400f-8ae3-cd39e377c82f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0f5f89ae-b473-41fd-8ac6-e2312001b3eb"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9137c6c4-4fe6-4728-949d-66259f42c3d0"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button13"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""86d0906f-425e-46d0-96b7-0ddcc4b71ccd"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button14"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f4d7b03b-91c1-4c6c-a22f-7b76f9a17fe6"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Hut_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""KeyAxis"",
                    ""id"": ""db8212e4-bb8c-4d50-a0b2-5c175c660299"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""982153c1-f267-44c0-9e1a-123e30db9563"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9c84bc0c-6eec-4a29-9468-7a81a1b628c2"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e7f77e11-f63b-4147-98ac-a5fcc640b8a3"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d809a101-985a-4ad0-a805-5d48cab1cb5b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hut_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""6fee98ad-e767-4c7e-835a-6ac6b9ccc33b"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Axis"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c24571b-65f3-4459-85c1-146571704a23"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Number_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd08abf9-f688-4680-9b4e-65b30d589f5a"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""Number_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""038d5546-7bc3-49ab-a9a5-5219985c4e27"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Number_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2b5840b-e6af-4543-a4cb-f567dab6fa74"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Number_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30b32f13-c3ba-4b89-bd1f-f43ab3d13a15"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Number_5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cec636db-cdd7-4cb7-9937-b4e98f251b31"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Number_6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d72e073e-ff0b-42f3-9276-0d6b78d72069"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Container_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""660e07ee-0823-4675-b533-a9b78e4573b3"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Container_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac0fefd1-72f0-4b36-8fb5-df305effc81b"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Container_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66cc74ca-00b2-427f-a61e-82a5223f663e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd0db01d-fbc3-4267-8dbd-aceefdf85d94"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5a386d3-685d-4bf7-92f0-7d1d32af0f5d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Collect_mode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85bf0cab-02d2-47a7-a505-bee35fd3a07c"",
                    ""path"": ""<VirtualMouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4d8c054-5d1d-4c76-ab0f-fb7af96228ff"",
                    ""path"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main"",
                    ""action"": ""TriggerDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fa7dff3-b8c3-4e08-8ad9-e1901f1f209a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Out"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Moving"",
                    ""id"": ""7066ad15-d20c-4d92-a449-ceecf56df2f0"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AxisWasd"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""118a7181-9553-4d80-8543-f0c6a2b84e8a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;Main"",
                    ""action"": ""AxisWasd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""226a9fcc-672a-4924-b79d-773e0e80c62a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;Main"",
                    ""action"": ""AxisWasd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""134024d5-166a-49ba-8f95-5fcea3366d0f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;Main"",
                    ""action"": ""AxisWasd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""da812dac-d51b-40a0-aba7-ec632c89e84e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;Main"",
                    ""action"": ""AxisWasd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""ba8eefe5-421d-4212-9ff5-11127e80c7ff"",
            ""actions"": [
                {
                    ""name"": ""LeftButton"",
                    ""type"": ""Button"",
                    ""id"": ""6598c82c-d0ee-405b-ac94-2f7abd9d483e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6f071011-5e17-4184-86a3-ee048cbda8fc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouse"",
                    ""type"": ""Button"",
                    ""id"": ""dd9b71c9-ce4b-4acf-9f58-4f2941a592be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3fae2f12-9689-4065-9c25-232256505039"",
                    ""path"": ""<VirtualMouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""LeftButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e2ff593d-de2e-4482-aa19-89ac9b78cd75"",
                    ""path"": ""<VirtualMouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Main;Keyboard"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""039612cd-123b-4342-b0e5-a1c55f2b8a62"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard;Main"",
                    ""action"": ""LeftMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Main"",
            ""bindingGroup"": ""Main"",
            ""devices"": [
                {
                    ""devicePath"": ""<HID::© Alex Oz 2012-2020  VKB-Sim Space Gunfighter >"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Controller
        m_Controller = asset.FindActionMap("Controller", throwIfNotFound: true);
        m_Controller_Trigger = m_Controller.FindAction("Trigger", throwIfNotFound: true);
        m_Controller_Button_1 = m_Controller.FindAction("Button_1", throwIfNotFound: true);
        m_Controller_Button_2 = m_Controller.FindAction("Button_2", throwIfNotFound: true);
        m_Controller_Button_3 = m_Controller.FindAction("Button_3", throwIfNotFound: true);
        m_Controller_Button_4 = m_Controller.FindAction("Button_4", throwIfNotFound: true);
        m_Controller_Hut_1 = m_Controller.FindAction("Hut_1", throwIfNotFound: true);
        m_Controller_Hut_2 = m_Controller.FindAction("Hut_2", throwIfNotFound: true);
        m_Controller_Hut_3 = m_Controller.FindAction("Hut_3", throwIfNotFound: true);
        m_Controller_Axis = m_Controller.FindAction("Axis", throwIfNotFound: true);
        m_Controller_Number_1 = m_Controller.FindAction("Number_1", throwIfNotFound: true);
        m_Controller_Number_2 = m_Controller.FindAction("Number_2", throwIfNotFound: true);
        m_Controller_Number_3 = m_Controller.FindAction("Number_3", throwIfNotFound: true);
        m_Controller_Number_4 = m_Controller.FindAction("Number_4", throwIfNotFound: true);
        m_Controller_Number_5 = m_Controller.FindAction("Number_5", throwIfNotFound: true);
        m_Controller_Number_6 = m_Controller.FindAction("Number_6", throwIfNotFound: true);
        m_Controller_Container_1 = m_Controller.FindAction("Container_1", throwIfNotFound: true);
        m_Controller_Container_2 = m_Controller.FindAction("Container_2", throwIfNotFound: true);
        m_Controller_Container_3 = m_Controller.FindAction("Container_3", throwIfNotFound: true);
        m_Controller_Up = m_Controller.FindAction("Up", throwIfNotFound: true);
        m_Controller_Down = m_Controller.FindAction("Down", throwIfNotFound: true);
        m_Controller_Collect_mode = m_Controller.FindAction("Collect_mode", throwIfNotFound: true);
        m_Controller_MousePos = m_Controller.FindAction("MousePos", throwIfNotFound: true);
        m_Controller_TriggerDown = m_Controller.FindAction("TriggerDown", throwIfNotFound: true);
        m_Controller_Out = m_Controller.FindAction("Out", throwIfNotFound: true);
        m_Controller_AxisWasd = m_Controller.FindAction("AxisWasd", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_LeftButton = m_UI.FindAction("LeftButton", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_LeftMouse = m_UI.FindAction("LeftMouse", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Controller
    private readonly InputActionMap m_Controller;
    private IControllerActions m_ControllerActionsCallbackInterface;
    private readonly InputAction m_Controller_Trigger;
    private readonly InputAction m_Controller_Button_1;
    private readonly InputAction m_Controller_Button_2;
    private readonly InputAction m_Controller_Button_3;
    private readonly InputAction m_Controller_Button_4;
    private readonly InputAction m_Controller_Hut_1;
    private readonly InputAction m_Controller_Hut_2;
    private readonly InputAction m_Controller_Hut_3;
    private readonly InputAction m_Controller_Axis;
    private readonly InputAction m_Controller_Number_1;
    private readonly InputAction m_Controller_Number_2;
    private readonly InputAction m_Controller_Number_3;
    private readonly InputAction m_Controller_Number_4;
    private readonly InputAction m_Controller_Number_5;
    private readonly InputAction m_Controller_Number_6;
    private readonly InputAction m_Controller_Container_1;
    private readonly InputAction m_Controller_Container_2;
    private readonly InputAction m_Controller_Container_3;
    private readonly InputAction m_Controller_Up;
    private readonly InputAction m_Controller_Down;
    private readonly InputAction m_Controller_Collect_mode;
    private readonly InputAction m_Controller_MousePos;
    private readonly InputAction m_Controller_TriggerDown;
    private readonly InputAction m_Controller_Out;
    private readonly InputAction m_Controller_AxisWasd;
    public struct ControllerActions
    {
        private @Joystick m_Wrapper;
        public ControllerActions(@Joystick wrapper) { m_Wrapper = wrapper; }
        public InputAction @Trigger => m_Wrapper.m_Controller_Trigger;
        public InputAction @Button_1 => m_Wrapper.m_Controller_Button_1;
        public InputAction @Button_2 => m_Wrapper.m_Controller_Button_2;
        public InputAction @Button_3 => m_Wrapper.m_Controller_Button_3;
        public InputAction @Button_4 => m_Wrapper.m_Controller_Button_4;
        public InputAction @Hut_1 => m_Wrapper.m_Controller_Hut_1;
        public InputAction @Hut_2 => m_Wrapper.m_Controller_Hut_2;
        public InputAction @Hut_3 => m_Wrapper.m_Controller_Hut_3;
        public InputAction @Axis => m_Wrapper.m_Controller_Axis;
        public InputAction @Number_1 => m_Wrapper.m_Controller_Number_1;
        public InputAction @Number_2 => m_Wrapper.m_Controller_Number_2;
        public InputAction @Number_3 => m_Wrapper.m_Controller_Number_3;
        public InputAction @Number_4 => m_Wrapper.m_Controller_Number_4;
        public InputAction @Number_5 => m_Wrapper.m_Controller_Number_5;
        public InputAction @Number_6 => m_Wrapper.m_Controller_Number_6;
        public InputAction @Container_1 => m_Wrapper.m_Controller_Container_1;
        public InputAction @Container_2 => m_Wrapper.m_Controller_Container_2;
        public InputAction @Container_3 => m_Wrapper.m_Controller_Container_3;
        public InputAction @Up => m_Wrapper.m_Controller_Up;
        public InputAction @Down => m_Wrapper.m_Controller_Down;
        public InputAction @Collect_mode => m_Wrapper.m_Controller_Collect_mode;
        public InputAction @MousePos => m_Wrapper.m_Controller_MousePos;
        public InputAction @TriggerDown => m_Wrapper.m_Controller_TriggerDown;
        public InputAction @Out => m_Wrapper.m_Controller_Out;
        public InputAction @AxisWasd => m_Wrapper.m_Controller_AxisWasd;
        public InputActionMap Get() { return m_Wrapper.m_Controller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControllerActions set) { return set.Get(); }
        public void SetCallbacks(IControllerActions instance)
        {
            if (m_Wrapper.m_ControllerActionsCallbackInterface != null)
            {
                @Trigger.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTrigger;
                @Trigger.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTrigger;
                @Trigger.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTrigger;
                @Button_1.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_1;
                @Button_1.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_1;
                @Button_1.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_1;
                @Button_2.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_2;
                @Button_2.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_2;
                @Button_2.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_2;
                @Button_3.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_3;
                @Button_3.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_3;
                @Button_3.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_3;
                @Button_4.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_4;
                @Button_4.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_4;
                @Button_4.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnButton_4;
                @Hut_1.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_1;
                @Hut_1.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_1;
                @Hut_1.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_1;
                @Hut_2.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_2;
                @Hut_2.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_2;
                @Hut_2.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_2;
                @Hut_3.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_3;
                @Hut_3.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_3;
                @Hut_3.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnHut_3;
                @Axis.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnAxis;
                @Axis.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnAxis;
                @Axis.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnAxis;
                @Number_1.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_1;
                @Number_1.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_1;
                @Number_1.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_1;
                @Number_2.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_2;
                @Number_2.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_2;
                @Number_2.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_2;
                @Number_3.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_3;
                @Number_3.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_3;
                @Number_3.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_3;
                @Number_4.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_4;
                @Number_4.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_4;
                @Number_4.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_4;
                @Number_5.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_5;
                @Number_5.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_5;
                @Number_5.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_5;
                @Number_6.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_6;
                @Number_6.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_6;
                @Number_6.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnNumber_6;
                @Container_1.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_1;
                @Container_1.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_1;
                @Container_1.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_1;
                @Container_2.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_2;
                @Container_2.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_2;
                @Container_2.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_2;
                @Container_3.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_3;
                @Container_3.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_3;
                @Container_3.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnContainer_3;
                @Up.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnUp;
                @Up.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnUp;
                @Up.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnUp;
                @Down.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDown;
                @Down.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDown;
                @Down.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnDown;
                @Collect_mode.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnCollect_mode;
                @Collect_mode.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnCollect_mode;
                @Collect_mode.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnCollect_mode;
                @MousePos.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnMousePos;
                @MousePos.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnMousePos;
                @MousePos.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnMousePos;
                @TriggerDown.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerDown;
                @TriggerDown.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerDown;
                @TriggerDown.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnTriggerDown;
                @Out.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnOut;
                @Out.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnOut;
                @Out.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnOut;
                @AxisWasd.started -= m_Wrapper.m_ControllerActionsCallbackInterface.OnAxisWasd;
                @AxisWasd.performed -= m_Wrapper.m_ControllerActionsCallbackInterface.OnAxisWasd;
                @AxisWasd.canceled -= m_Wrapper.m_ControllerActionsCallbackInterface.OnAxisWasd;
            }
            m_Wrapper.m_ControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Trigger.started += instance.OnTrigger;
                @Trigger.performed += instance.OnTrigger;
                @Trigger.canceled += instance.OnTrigger;
                @Button_1.started += instance.OnButton_1;
                @Button_1.performed += instance.OnButton_1;
                @Button_1.canceled += instance.OnButton_1;
                @Button_2.started += instance.OnButton_2;
                @Button_2.performed += instance.OnButton_2;
                @Button_2.canceled += instance.OnButton_2;
                @Button_3.started += instance.OnButton_3;
                @Button_3.performed += instance.OnButton_3;
                @Button_3.canceled += instance.OnButton_3;
                @Button_4.started += instance.OnButton_4;
                @Button_4.performed += instance.OnButton_4;
                @Button_4.canceled += instance.OnButton_4;
                @Hut_1.started += instance.OnHut_1;
                @Hut_1.performed += instance.OnHut_1;
                @Hut_1.canceled += instance.OnHut_1;
                @Hut_2.started += instance.OnHut_2;
                @Hut_2.performed += instance.OnHut_2;
                @Hut_2.canceled += instance.OnHut_2;
                @Hut_3.started += instance.OnHut_3;
                @Hut_3.performed += instance.OnHut_3;
                @Hut_3.canceled += instance.OnHut_3;
                @Axis.started += instance.OnAxis;
                @Axis.performed += instance.OnAxis;
                @Axis.canceled += instance.OnAxis;
                @Number_1.started += instance.OnNumber_1;
                @Number_1.performed += instance.OnNumber_1;
                @Number_1.canceled += instance.OnNumber_1;
                @Number_2.started += instance.OnNumber_2;
                @Number_2.performed += instance.OnNumber_2;
                @Number_2.canceled += instance.OnNumber_2;
                @Number_3.started += instance.OnNumber_3;
                @Number_3.performed += instance.OnNumber_3;
                @Number_3.canceled += instance.OnNumber_3;
                @Number_4.started += instance.OnNumber_4;
                @Number_4.performed += instance.OnNumber_4;
                @Number_4.canceled += instance.OnNumber_4;
                @Number_5.started += instance.OnNumber_5;
                @Number_5.performed += instance.OnNumber_5;
                @Number_5.canceled += instance.OnNumber_5;
                @Number_6.started += instance.OnNumber_6;
                @Number_6.performed += instance.OnNumber_6;
                @Number_6.canceled += instance.OnNumber_6;
                @Container_1.started += instance.OnContainer_1;
                @Container_1.performed += instance.OnContainer_1;
                @Container_1.canceled += instance.OnContainer_1;
                @Container_2.started += instance.OnContainer_2;
                @Container_2.performed += instance.OnContainer_2;
                @Container_2.canceled += instance.OnContainer_2;
                @Container_3.started += instance.OnContainer_3;
                @Container_3.performed += instance.OnContainer_3;
                @Container_3.canceled += instance.OnContainer_3;
                @Up.started += instance.OnUp;
                @Up.performed += instance.OnUp;
                @Up.canceled += instance.OnUp;
                @Down.started += instance.OnDown;
                @Down.performed += instance.OnDown;
                @Down.canceled += instance.OnDown;
                @Collect_mode.started += instance.OnCollect_mode;
                @Collect_mode.performed += instance.OnCollect_mode;
                @Collect_mode.canceled += instance.OnCollect_mode;
                @MousePos.started += instance.OnMousePos;
                @MousePos.performed += instance.OnMousePos;
                @MousePos.canceled += instance.OnMousePos;
                @TriggerDown.started += instance.OnTriggerDown;
                @TriggerDown.performed += instance.OnTriggerDown;
                @TriggerDown.canceled += instance.OnTriggerDown;
                @Out.started += instance.OnOut;
                @Out.performed += instance.OnOut;
                @Out.canceled += instance.OnOut;
                @AxisWasd.started += instance.OnAxisWasd;
                @AxisWasd.performed += instance.OnAxisWasd;
                @AxisWasd.canceled += instance.OnAxisWasd;
            }
        }
    }
    public ControllerActions @Controller => new ControllerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_LeftButton;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_LeftMouse;
    public struct UIActions
    {
        private @Joystick m_Wrapper;
        public UIActions(@Joystick wrapper) { m_Wrapper = wrapper; }
        public InputAction @LeftButton => m_Wrapper.m_UI_LeftButton;
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @LeftMouse => m_Wrapper.m_UI_LeftMouse;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @LeftButton.started -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftButton;
                @LeftButton.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftButton;
                @LeftButton.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftButton;
                @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @LeftMouse.started -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftMouse;
                @LeftMouse.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftMouse;
                @LeftMouse.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnLeftMouse;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LeftButton.started += instance.OnLeftButton;
                @LeftButton.performed += instance.OnLeftButton;
                @LeftButton.canceled += instance.OnLeftButton;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @LeftMouse.started += instance.OnLeftMouse;
                @LeftMouse.performed += instance.OnLeftMouse;
                @LeftMouse.canceled += instance.OnLeftMouse;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_MainSchemeIndex = -1;
    public InputControlScheme MainScheme
    {
        get
        {
            if (m_MainSchemeIndex == -1) m_MainSchemeIndex = asset.FindControlSchemeIndex("Main");
            return asset.controlSchemes[m_MainSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IControllerActions
    {
        void OnTrigger(InputAction.CallbackContext context);
        void OnButton_1(InputAction.CallbackContext context);
        void OnButton_2(InputAction.CallbackContext context);
        void OnButton_3(InputAction.CallbackContext context);
        void OnButton_4(InputAction.CallbackContext context);
        void OnHut_1(InputAction.CallbackContext context);
        void OnHut_2(InputAction.CallbackContext context);
        void OnHut_3(InputAction.CallbackContext context);
        void OnAxis(InputAction.CallbackContext context);
        void OnNumber_1(InputAction.CallbackContext context);
        void OnNumber_2(InputAction.CallbackContext context);
        void OnNumber_3(InputAction.CallbackContext context);
        void OnNumber_4(InputAction.CallbackContext context);
        void OnNumber_5(InputAction.CallbackContext context);
        void OnNumber_6(InputAction.CallbackContext context);
        void OnContainer_1(InputAction.CallbackContext context);
        void OnContainer_2(InputAction.CallbackContext context);
        void OnContainer_3(InputAction.CallbackContext context);
        void OnUp(InputAction.CallbackContext context);
        void OnDown(InputAction.CallbackContext context);
        void OnCollect_mode(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
        void OnTriggerDown(InputAction.CallbackContext context);
        void OnOut(InputAction.CallbackContext context);
        void OnAxisWasd(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnLeftButton(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnLeftMouse(InputAction.CallbackContext context);
    }
}
